### PR TITLE
Add exception handling to kinesis comms

### PR DESCRIPTION
**Pull request by acron0**

### CODE REVIEW

**Comment by otfrom** [comment]
What are the cases in which this will throw an exception?

**Comment by acron0** [comment]
@otfrom When a user's handler function does so, or for some reason it's can't reach Kinesis

**Comment by otfrom** [comment]
If we can't reach kinesis don't we want some kind of back off, or to actually bring the process down? Is this just an intermittent thing? atm, the way this is written if we lose the connection to kinesis we'll continue to accept messages on the asyn channel and just log that we haven't passed them on, but other than that there is no communication to any caller IIUC

**Comment by acron0** [comment]
@otfrom In an ideal world, yes, we'd start either dumping these msgs to disk or memory until we can connect again. The PR was more motivated by handlers throwing exceptions - actually though there is already an exception catch in message.clj so this is largely redundant.

**Comment by otfrom** [comment]
Looking at the docs: http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/kinesis/AmazonKinesis.html#putRecord-java.lang.String-java.nio.ByteBuffer-java.lang.String-java.lang.String-

It looks like the 3 scenarios are: 

- ResourceNotFound - probably bad config unless you are creating streams on the fly
- InvalidArgumentException - bad coding
- ProvisionedThroughputExceededException - hammering it too hard. Either back off or up the quota 

atm, this is going to swallow the exception and prevent any calling code from handling this

**Pull request merged**
