### PR TITLE
Add support for handling all events

### PR DESCRIPTION
**Pull request by acron0**
Add a new arity to `add-event-handler!` so that you do not need to specify an event key and version. Use sparingly.

### CODE REVIEW

**Comment by mantree** [comment]
Wldn't it be better to submit a range of event/version pairs that are accepted? A goal catch doesn't seem right.

**Comment by acron0** [comment]
No, this functionality is required by the gateway in order to forward events back to the frontend. The gateway has no idea what the events or versions might be, just that if it receives one addressed (via command ID) to a websocket connection it knows about, it is to forward it on.

**Comment by mantree** [comment]
But not all events will be for the frontend.

**Comment by acron0** [comment]
Key presence now checked for inside kixi.comms

**Pull request merged**
